// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7tdwVK3fuMclkveJB7EtIDoCRdJOPGlc',
    appId: '1:18398146893:web:3e9250df38245908538704',
    messagingSenderId: '18398146893',
    projectId: 'mamo-9fa7a',
    authDomain: 'mamo-9fa7a.firebaseapp.com',
    storageBucket: 'mamo-9fa7a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Fe8siw94eIs6uyPbpGnDbxOz-EY9U8k',
    appId: '1:18398146893:android:42a06866b051033c538704',
    messagingSenderId: '18398146893',
    projectId: 'mamo-9fa7a',
    storageBucket: 'mamo-9fa7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9txMsKs89JDTVWKvkPNYCVCQZcIGCsN4',
    appId: '1:18398146893:ios:362e4899a95f3c55538704',
    messagingSenderId: '18398146893',
    projectId: 'mamo-9fa7a',
    storageBucket: 'mamo-9fa7a.firebasestorage.app',
    iosBundleId: 'com.mamo.mamo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9txMsKs89JDTVWKvkPNYCVCQZcIGCsN4',
    appId: '1:18398146893:ios:362e4899a95f3c55538704',
    messagingSenderId: '18398146893',
    projectId: 'mamo-9fa7a',
    storageBucket: 'mamo-9fa7a.firebasestorage.app',
    iosBundleId: 'com.mamo.mamo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7tdwVK3fuMclkveJB7EtIDoCRdJOPGlc',
    appId: '1:18398146893:web:7abffdeb4bd92a10538704',
    messagingSenderId: '18398146893',
    projectId: 'mamo-9fa7a',
    authDomain: 'mamo-9fa7a.firebaseapp.com',
    storageBucket: 'mamo-9fa7a.firebasestorage.app',
  );
}
